import "./MessageBoard.css";

const EXAMPLE_MESSAGES = [
  {
    agent: "Coordinator",
    message: "Project operations started.",
  },
  {
    agent: "ResearchAgent",
    message: "Researching available sources for the current task.",
  },
  {
    agent: "MarketingAgent",
    message: "Waiting for research results before beginning content planning.",
  },
  {
    agent: "ResearchAgent",
    message: "Completed the first research subtask.",
  },
  {
    agent: "FinanceAgent",
    message: "Current project usage remains within the configured budget.",
  },
  {
    agent: "DevelopmentAgent",
    message: "Received a request from the Coordinator.",
  },
  {
    agent: "DevelopmentAgent",
    message: "Completed the requested implementation task.",
  },
  {
    agent: "ResearchAgent",
    message: "One external request returned an error and will be retried.",
  },
  {
    agent: "Coordinator",
    message: "Research results have been forwarded to the next task.",
  },
  {
    agent: "MarketingAgent",
    message: "Content planning is now in progress.",
  },
  {
    agent: "FinanceAgent",
    message: "Usage update recorded for the current operation.",
  },
  {
    agent: "Coordinator",
    message: "Project remains active. Several subtasks are still running.",
  },
];

function MessageBoard() {
  return (
    <div
      className="message-board"
      role="region"
      aria-label="Project Communications"
    >
      <div className="message-board-header">
        <h2>Communications</h2>
      </div>

      <div className="message-board-content">
        <p className="message-board-description">
          Project-wide communications will appear here, including progress
          updates, completed subtasks, agent requests, agent-to-agent
          communications, successful actions, errors, usage updates, budget
          warnings, stopped operations, and other important project events.
          This board is intended for important team-level communication rather
          than every internal event generated by every agent.
        </p>


        <div className="example-message-list">
          {EXAMPLE_MESSAGES.map((item, index) => (
            <div
              className="example-message"
              key={`${item.agent}-${index}`}
            >
              <strong>{item.agent}:</strong>{" "}
              <span>{item.message}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default MessageBoard;